INSERT INTO SAMPLE(NAME, ALTERNAME, ENABLED) VALUES ('americano', 'americano2', TRUE);
INSERT INTO SAMPLE(NAME, ALTERNAME, ENABLED) VALUES ('latte', 'latte2', TRUE);
INSERT INTO SAMPLE(NAME, ALTERNAME, ENABLED) VALUES ('tea', 'tea2', TRUE);
INSERT INTO SAMPLE(NAME, ALTERNAME, ENABLED) VALUES ('choco', 'choco2', FALSE);