INSERT INTO SAMPLE(NICKNAME, NAME, ENABLED) VALUES ('blah', 'sam', TRUE);
INSERT INTO SAMPLE(NICKNAME, NAME, ENABLED) VALUES ('gogogo', 'lenard', TRUE);
INSERT INTO SAMPLE(NICKNAME, NAME, ENABLED) VALUES ('coffee', 'penny', TRUE);