INSERT INTO SAMPLE(SAMPLE_ID, NAME, ENABLED) VALUES ('1', 'jonghyeon', TRUE);
INSERT INTO SAMPLE(SAMPLE_ID, NAME, ENABLED) VALUES ('2', '_sCream', TRUE);
INSERT INTO SAMPLE(SAMPLE_ID, NAME, ENABLED) VALUES ('3', 'JJ', TRUE);