INSERT INTO SAMPLE(NAME, ALTERNAME, ENABLED) VALUES ('coffee', 'coffee2', TRUE);
INSERT INTO SAMPLE(NAME, ALTERNAME, ENABLED) VALUES ('latte', 'latte2', TRUE);
INSERT INTO SAMPLE(NAME, ALTERNAME, ENABLED) VALUES ('tea', 'tea2', TRUE);